apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: localstack
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        # Getting the accessKeyID and secretAccessKey from an already created Kubernetes Secret
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: default
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: default